# Generated by Django 3.2.3 on 2021-06-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeus',
            name='message',
            field=models.TextField(max_length=300, verbose_name='Сообщение'),
        ),
    ]
