# Generated by Django 3.2.3 on 2021-05-22 04:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsandanswers',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questionsandanswers',
            name='question',
            field=models.CharField(max_length=100, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='writeus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Контактный адрес почты'),
        ),
        migrations.AlterField(
            model_name='writeus',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия, имя, отчество'),
        ),
        migrations.AlterField(
            model_name='writeus',
            name='message',
            field=models.TextField(max_length=300, verbose_name='Ваше сообщение'),
        ),
        migrations.AlterField(
            model_name='writeus',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Контактный номер телефона'),
        ),
    ]
