# Generated by Django 3.2 on 2021-05-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SectorChoices',
            new_name='Sector',
        ),
        migrations.AlterModelOptions(
            name='businessprofile',
            options={},
        ),
    ]
