# Generated by Django 3.2 on 2021-05-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210522_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='sector',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='sector',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sector_set', to='users.sector', verbose_name='Сектор деятельности'),
        ),
    ]
