# Generated by Django 3.2 on 2021-05-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210511_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='employers',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='region',
            field=models.CharField(choices=[('Все', 'Весь Кыргызстан'), ('Чуй', 'Чуйская область'), ('Нарын', 'Нарынская область'), ('Баткен', 'Баткенская область'), ('Талас', 'Таласская область'), ('Ош', 'Ошская область'), ('Джалал-Абад', 'Джалал-Абадская область'), ('Иссык-Куль', 'Иссык-Кульская область')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='sector',
            field=models.ManyToManyField(blank=True, to='users.SectorChoices'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='turnover',
            field=models.CharField(choices=[('до 100 000', 'до 100 000'), ('до 500 000', 'до 100 000'), ('до 1 000 000', 'до 1 000 000'), ('до 5 000 000', 'до 5 000 000'), ('до 10 000 000', 'до 10 000 000'), ('более 10 000 000', 'более 10 000 000')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='scope',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='services',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
