# Generated by Django 3.2 on 2021-05-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210522_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='sector',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='sector',
            field=models.ManyToManyField(blank=True, to='users.Sector', verbose_name='Сектор деятельности'),
        ),
    ]
