# Generated by Django 3.2 on 2021-06-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210522_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='year',
            field=models.DateField(blank=True, null=True, verbose_name='Год основания'),
        ),
    ]
