# Generated by Django 3.2 on 2021-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210516_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='year',
            field=models.DateField(blank=True),
        ),
    ]
