# Generated by Django 3.2 on 2021-06-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_providerprofile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/provider/logo/%d%m%Y/', verbose_name='Логотип'),
        ),
    ]
