# Generated by Django 3.2 on 2021-05-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210516_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
