# Generated by Django 3.2 on 2021-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210516_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/provider/logo/%d%m%Y/'),
        ),
    ]
