# Generated by Django 3.2 on 2021-05-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_providerprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='as_business',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='as_provider',
            field=models.BooleanField(default=True),
        ),
    ]
