# Generated by Django 3.2 on 2021-05-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_providerprofile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='employers',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
