# Generated by Django 3.2.3 on 2021-06-16 12:41

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя мероприятия')),
                ('date', models.DateField(verbose_name='Дата мероприятия')),
                ('time', models.TimeField(verbose_name='Начало')),
                ('location', models.CharField(max_length=100, verbose_name='Место')),
                ('event_format', models.CharField(choices=[('Оффлайн', 'Оффлайн'), ('Онлайн', 'Онлайн')], default='Оффлайн', max_length=7, verbose_name='Формат мероприятия')),
                ('sum', models.PositiveIntegerField(verbose_name='Стоимость входа')),
                ('event_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[250, 250], upload_to='images/event_images/<django.db.models.fields.CharField>-%d%m%Y', verbose_name='Плакат мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_text', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('commentator_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('commentator_email', models.EmailField(max_length=254, verbose_name='Контактный адрес почты')),
            ],
            options={
                'verbose_name': 'Комментарий мероприятия',
                'verbose_name_plural': 'Комментарии мероприятий',
            },
        ),
    ]
