# Generated by Django 3.2.3 on 2021-05-20 06:05

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='picture',
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[250, 250], upload_to='images/events_images/<django.db.models.fields.CharField>-%d%m%Y'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sum',
            field=models.PositiveIntegerField(),
        ),
    ]
