# Generated by Django 3.2.3 on 2021-06-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='commentator_email',
            field=models.EmailField(max_length=254, verbose_name='Контактный адрес почты'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='commentator_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='commentator_text',
            field=models.TextField(max_length=500, verbose_name='Комментарий'),
        ),
    ]
