# Generated by Django 3.2.3 on 2021-05-20 06:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210520_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[350, 250], upload_to='images/event_images/<django.db.models.fields.CharField>-%d%m%Y'),
        ),
    ]
