# Generated by Django 3.2.3 on 2021-05-22 04:16

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[250, 250], upload_to='images/event_images/<django.db.models.fields.CharField>-%d%m%Y', verbose_name='Плакат мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Местонахождение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sum',
            field=models.PositiveIntegerField(verbose_name='Стоимость входа'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(verbose_name='Начало'),
        ),
    ]
