# Generated by Django 3.2.3 on 2021-05-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210522_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_format',
            field=models.CharField(choices=[('Оффлайн', 'Оффлайн'), ('Онлайн', 'Онлайн')], default='Оффлайн', max_length=7, verbose_name='Формат мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Место'),
        ),
    ]
