# Generated by Django 3.2.3 on 2021-06-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fullname',
            field=models.CharField(default=1, max_length=50, verbose_name='Настоящее имя'),
            preserve_default=False,
        ),
    ]
