# Generated by Django 3.2.3 on 2021-06-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_author_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='username',
        ),
    ]
