# Generated by Django 3.2.3 on 2021-05-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210527_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(max_length=150),
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Гранты/инвестиции', 'Гранты/инвестиции'), ('Купля-продажа бизнеса', 'Купля-продажа бизнеса'), ('Юридические вопросы', 'Юридические вопросы'), ('Партнерство и др', 'Партнерство и др')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
