# Generated by Django 3.2.3 on 2021-05-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='Описание категории:'),
        ),
    ]
