# Generated by Django 3.2.3 on 2021-05-28 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0008_auto_20210528_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Ответ автору поста', 'verbose_name_plural': 'Ответ авторам постов'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост автора на форуме', 'verbose_name_plural': 'Посты авторов на форуме'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Ответ комментатору', 'verbose_name_plural': 'Ответы комментаторам'},
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(max_length=150, verbose_name='Немного о себе'),
        ),
        migrations.AlterField(
            model_name='author',
            name='fullname',
            field=models.CharField(blank=True, max_length=40, verbose_name='Настоящее имя пользователя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, size=[50, 80], upload_to='authors', verbose_name='Изображение профиля'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='Описание категории:', verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.author', verbose_name='Юзер, которому вы напишите комментарий'),
        ),
        migrations.AlterField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Статус отправки поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='forum.Category', verbose_name='Категория поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=300, verbose_name='Содержание поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тег поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=400, verbose_name='Имя поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.author', verbose_name=' Имя юзера, создающий пост'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.author', verbose_name='Юзер, которому вы напишите комментарий'),
        ),
    ]
