# Generated by Django 3.2.3 on 2021-05-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210528_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Ответ автору поста', 'verbose_name_plural': 'Ответы авторам постов'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Ваш комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, to='forum.Reply', verbose_name='Комментарии юзеров'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='forum.Comment', verbose_name='Комментарии юзеров к автору поста'),
        ),
    ]
