# Generated by Django 3.2.3 on 2021-05-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20210529_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(blank=True, to='forum.Reply', verbose_name='Комментарии юзеров'),
        ),
    ]
