# Generated by Django 3.2.3 on 2021-05-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_post_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='replies',
        ),
    ]
