# Generated by Django 3.2 on 2021-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_answer', models.IntegerField(choices=[(0, 0), (20, 20), (40, 40), (60, 60), (80, 80), (100, 100)], verbose_name='Ответ пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='ResultPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pass_poll', models.DateTimeField(auto_now_add=True)),
                ('avg_points', models.IntegerField(default=0)),
            ],
        ),
    ]
