# Generated by Django 3.2.3 on 2021-06-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultpoll',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Вопрос пользователю'),
        ),
        migrations.AlterField(
            model_name='resultpoll',
            name='answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.answer', verbose_name='Ответ пользователя'),
        ),
        migrations.AlterField(
            model_name='resultpoll',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Вопрос пользователю'),
        ),
    ]
