# Generated by Django 3.2.3 on 2021-06-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответы пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='title',
        ),
        migrations.AlterField(
            model_name='question',
            name='max_points',
            field=models.FloatField(default=100),
        ),
    ]
