# Generated by Django 3.2.3 on 2021-06-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210616_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultpoll',
            old_name='points',
            new_name='avg_points',
        ),
    ]
