# Generated by Django 3.2 on 2021-08-31 18:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_сonsultationform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Список вопросов'},
        ),
        migrations.AlterModelOptions(
            name='resultpoll',
            options={'verbose_name': 'Результат опроса', 'verbose_name_plural': 'Результаты опросов'},
        ),
        migrations.AlterModelOptions(
            name='сonsultationform',
            options={'verbose_name': 'Обращение через форму для консультации', 'verbose_name_plural': 'Все обращения через форму для консультаций'},
        ),
        migrations.AlterField(
            model_name='сonsultationform',
            name='messanger',
            field=models.CharField(max_length=30, verbose_name="Whats'App или Telegram"),
        ),
        migrations.AlterField(
            model_name='сonsultationform',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='сonsultationform',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'),
        ),
    ]
