# Generated by Django 3.2 on 2021-06-13 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_name', models.CharField(max_length=50, verbose_name='Имя гранта')),
                ('grant_sum', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000)], verbose_name='Сумма гранта')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('Сом', 'KGS'), ('Евро', 'EUR'), ('Рубль', 'RUB')], default='Сом', max_length=5, verbose_name='Валюта')),
                ('grant_deadline', models.CharField(max_length=20, verbose_name='Срок гранта')),
                ('grant_description', models.TextField(max_length=300, verbose_name='Описание гранта')),
            ],
            options={
                'verbose_name': 'Грант',
                'verbose_name_plural': 'Гранты',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_name', models.CharField(max_length=50, verbose_name='Имя инвестиции')),
                ('invest_sum', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000)], verbose_name='Сумма инвестиции')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('Сом', 'KGS'), ('Евро', 'EUR'), ('Рубль', 'RUB')], default='Сом', max_length=5, verbose_name='Валюта')),
                ('invest_deadline', models.CharField(max_length=20, verbose_name='Срок инвестиции')),
                ('invest_description', models.TextField(max_length=300, verbose_name='Описание инвестиции')),
            ],
            options={
                'verbose_name': 'Инвестиция',
                'verbose_name_plural': 'Инвестиции',
            },
        ),
    ]
