# Generated by Django 3.2.3 on 2021-05-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_name', models.CharField(max_length=50, verbose_name='Имя гранта')),
                ('grant_sum', models.PositiveIntegerField(verbose_name='Сумма гранта')),
                ('grant_deadline', models.CharField(max_length=20, verbose_name='Срок гранта')),
                ('grant_description', models.TextField(max_length=300, verbose_name='Описание гранта')),
            ],
            options={
                'verbose_name': 'Грант',
                'verbose_name_plural': 'Гранты',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_name', models.CharField(max_length=50, verbose_name='Имя инвестиции')),
                ('invest_sum', models.PositiveIntegerField(verbose_name='Сумма инвестиции')),
                ('invest_deadline', models.CharField(max_length=20, verbose_name='Срок инвестиции')),
                ('invest_description', models.TextField(max_length=300, verbose_name='Описание инвестиции')),
            ],
            options={
                'verbose_name': 'Инвестиция',
                'verbose_name_plural': 'Инвестиций',
            },
        ),
    ]
