# Generated by Django 3.2.3 on 2021-05-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants_and_investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'verbose_name': 'Инвестиция', 'verbose_name_plural': 'Инвестиции'},
        ),
    ]
