# Generated by Django 3.2.3 on 2021-06-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_and_investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantInvestmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_text', models.TextField(max_length=500, verbose_name='Ваш комментарий')),
                ('commentator_name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('commentator_email', models.EmailField(max_length=254, verbose_name='Ваш контактный адрес почты')),
            ],
            options={
                'verbose_name': 'Комментарий гранта/инвестиции',
                'verbose_name_plural': 'Комментарии грантов/инвестиций',
            },
        ),
    ]
