# Generated by Django 3.2.3 on 2021-05-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_and_investments', '0002_alter_investment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='grant_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма гранта'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='invest_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма инвестиции'),
        ),
    ]
