# Generated by Django 3.2.3 on 2021-05-22 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_and_investments', '0004_auto_20210522_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='grant_sum',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000)], verbose_name='Сумма гранта'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='invest_sum',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(10000000)], verbose_name='Сумма инвестиции'),
        ),
    ]
