# Generated by Django 3.2.3 on 2021-05-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_and_investments', '0005_auto_20210522_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('Сом', 'Сом'), ('Евро', 'Евро'), ('Рубль', 'Рубль')], default='Сом', max_length=5, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('Сом', 'Сом'), ('Евро', 'Евро'), ('Рубль', 'Рубль')], default='Сом', max_length=5, verbose_name='Валюта'),
        ),
    ]
