# Generated by Django 3.2.3 on 2021-05-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants_and_investments', '0006_auto_20210522_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('Сом', 'KGS'), ('Евро', 'EUR'), ('Рубль', 'RUB')], default='Сом', max_length=5, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('Сом', 'KGS'), ('Евро', 'EUR'), ('Рубль', 'RUB')], default='Сом', max_length=5, verbose_name='Валюта'),
        ),
    ]
