# Generated by Django 3.2 on 2021-07-12 17:46

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Набор изображений',
                'verbose_name_plural': 'Наборы изображений',
            },
        ),
        migrations.CreateModel(
            name='BusinessAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('Сом', 'Сом')], default='USD', max_length=3, verbose_name='Валюта')),
                ('completed', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет'), ('Оставить', 'Оставить')], default='Нет', max_length=8, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Объявление МСБ',
                'verbose_name_plural': 'Объявления МСБ',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Категория')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[350, 250], upload_to='images/adverts/%d%m%Y')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('Сом', 'Сом')], default='USD', max_length=3, verbose_name='Валюта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_advert_category', to='adverts.category', verbose_name='Категория')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='adverts.album', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Объявление провайдера',
                'verbose_name_plural': 'Объявления провайдеров',
            },
        ),
    ]
