# Generated by Django 3.2 on 2021-05-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradvert',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
