# Generated by Django 3.2.3 on 2021-05-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_alter_useradvert_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Название категории'),
        ),
    ]
