# Generated by Django 3.2 on 2021-05-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradvert',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
