# Generated by Django 3.2.3 on 2021-05-23 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_auto_20210522_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradvert',
            options={'verbose_name': 'Объявление от пользователя', 'verbose_name_plural': 'Объявления от пользователей'},
        ),
        migrations.AlterField(
            model_name='useradvert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert_category', to='adverts.category', verbose_name='Категория объявления'),
        ),
        migrations.AlterField(
            model_name='useradvert',
            name='completed',
            field=models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет'), ('Оставить', 'Оставить')], default='Нет', max_length=8, verbose_name='Актуальность объявления'),
        ),
        migrations.AlterField(
            model_name='useradvert',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('Сом', 'Сом')], default='USD', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='useradvert',
            name='description',
            field=models.TextField(verbose_name='Описание объявления'),
        ),
        migrations.AlterField(
            model_name='useradvert',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название объявления'),
        ),
        migrations.AlterField(
            model_name='useradvert',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='useradvert',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Умения'),
        ),
    ]
