# Generated by Django 3.2 on 2021-05-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_alter_useradvert_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
