# This is a basic workflow to help you get started with Actions

name: Deploy on dev server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev_develop ]
  pull_request:
    branches: [ dev_develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: /var/www/connect4pro

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: [self-hosted, deploy]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Pull from git
        run: |
          git checkout .
          git pull

      # Run migrations
      - name: Run migrations
        run: |
          . venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate
